config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  require 'api_constraints'
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints:ApiConstraints.new(version: 1, default: true) do
      resources :api
      resources :users
    end
  end

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :account_activation, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Home", root_path %>
  <nav>
    <ul>
      <% if logged_in? %>
        <li><%= link_to "#{current_user.full_name}", edit_user_path(current_user) %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<%= yield %>

</body>
</html>